"use client";
import { useState } from "react";

type Item = { id: number; nodeId: number; contentType: string; body: string; model: string; promptVersion: string; citation: string; heading: string };
export function AdminReview() {
  const [password, setPassword] = useState(""); const [items, setItems] = useState<Item[]>([]); const [message, setMessage] = useState("Enter the review password.");
  async function load() { const response = await fetch("/api/admin/ai-content", { headers: { "x-admin-password": password } }); const result = await response.json(); if (response.ok) { setItems(result.items); setMessage(`${result.items.length} drafts ready.`); } else setMessage(result.error); }
  async function act(id: number, action: string) { const response = await fetch("/api/admin/ai-content", { method: "POST", headers: { "content-type": "application/json", "x-admin-password": password }, body: JSON.stringify({ id, action }) }); if (response.ok) { setItems((current) => current.filter((item) => item.id !== id)); setMessage(`${action} complete.`); } else setMessage((await response.json()).error); }
  return <div><div className="paper-card rounded-2xl p-5 flex flex-wrap gap-3 items-end"><label className="grow"><span className="eyebrow">Admin password</span><input data-testid="admin-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="block mt-2 w-full rounded-lg border p-3 bg-white" /></label><button data-testid="load-drafts" onClick={load} className="button button-dark">Load drafts</button></div><p role="status" className="mt-4 font-bold">{message}</p>
    <div className="space-y-5 mt-7">{items.map((item) => <article data-testid="review-item" className="paper-card rounded-2xl p-6" key={item.id}><p className="eyebrow">{item.citation} · {item.contentType}</p><h2 className="serif text-2xl font-black mt-2">{item.heading}</h2><div className="mt-4 whitespace-pre-line leading-relaxed">{item.body}</div><p className="mt-4 text-xs text-[#68736d]">{item.model} · {item.promptVersion}</p><div className="flex gap-2 mt-5"><button data-testid="publish-draft" onClick={() => act(item.id, "publish")} className="button vote-keep">Publish</button><button onClick={() => act(item.id, "reject")} className="button vote-dissolve">Reject</button><button onClick={() => act(item.id, "regenerate")} className="button">Regenerate</button></div></article>)}</div>
  </div>;
}
